export const LEVEL_AREA_LIST: ReadonlyArray<string> = [
	'',
	'Appie Foothills',
	'Banquet Rainforest',
	'Brekkie',
	'Brew Path',
	'Brunch Canyon',
	'Dessert Mountain',
	'Dessert Peak',
	'Dinners',
	'Elevenses',
	'Feast',
	'Grub Caverns',
	'Grub Deep',
	'Gulp Swamp',
	'Luncheon',
	'Nibble Tunnel',
	'Potluck',
	'Simmer Springs',
	'Sips River',
	'Spoons Island',
	'Supper Woods',
	'Teatime Meadows',
	'The Big Drink',
	'Wielder Temple',
	'Wielder Tower',
	'Yum Cave',
	'none',
];
