// @flow strict

export type DogHatType = {
	internalName: string,
	externalName: string,
	imageIndex: number,
	imageWithPaddingPath?: string,

	layer2ImagePath?: string,
	showHair?: number,
	showHairExtraImagePath?: string,
};

export const DOG_HAT_LIST: $ReadOnlyArray<DogHatType> = [
	{
		internalName: 'None',
		externalName: 'None',
		imageIndex: -1,
	},
	// {
	// 	internalName: 'Custom Hat',
	// 	externalName: 'Custom Hat',
	// 	imageIndex: 0,
	// 	imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_0.png'),
	// 	showHair: 2,
	// },
	{
		internalName: 'Bandana',
		externalName: 'Bandana (default)',
		imageIndex: 0,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_0.png'),
	},
	{
		internalName: 'Beanie',
		externalName: 'Beanie',
		imageIndex: 1,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_1.png'),
	},
	{
		internalName: 'Brimcap',
		externalName: 'Brimcap',
		imageIndex: 2,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_2.png'),
	},
	{
		internalName: 'Strawhat',
		externalName: 'Strawhat',
		imageIndex: 3,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_3.png'),
		showHair: 2,
	},
	{
		internalName: 'Sunhat',
		externalName: 'Sunhat',
		imageIndex: 4,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_4.png'),
		showHair: 2,
	},
	{
		internalName: 'Headband',
		externalName: 'Headband',
		imageIndex: 8,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_8.png'),
		showHair: 1,
	},
	{
		internalName: 'Bow',
		externalName: 'Bow',
		imageIndex: 9,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_9.png'),
		showHair: 1,
	},
	{
		internalName: 'Scarf',
		externalName: 'Scarf',
		imageIndex: -1,
		layer2ImagePath: require('../images/clothes_padding/sprDog_body2_2.png'),
	},
	{
		internalName: 'Kerchief',
		externalName: 'Kerchief',
		imageIndex: -1,
		layer2ImagePath: require('../images/clothes_padding/sprDog_body2_1.png'),
	},
	{
		internalName: 'Antenna',
		externalName: 'Antenna',
		imageIndex: 12,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_12.png'),
	},
	{
		internalName: 'Flower',
		externalName: 'Flower',
		imageIndex: 13,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_13.png'),
		showHair: 1,
	},
	{
		internalName: 'Howdy',
		externalName: 'Howdy',
		imageIndex: 14,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_14.png'),
		showHair: 2,
	},
	{
		internalName: 'Shades',
		externalName: 'Shades',
		imageIndex: 15,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_15.png'),
		showHair: 1,
	},
	{
		internalName: 'Tinted Shades',
		externalName: 'Tinted Shades',
		imageIndex: 16,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_16.png'),
		showHair: 1,
	},
	{
		internalName: 'Line Shades',
		externalName: 'Line Shades',
		imageIndex: 17,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_17.png'),
		showHair: 1,
	},
	{
		internalName: 'Big Shades',
		externalName: 'Big Shades',
		imageIndex: 18,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_18.png'),
		showHair: 1,
	},
	{
		internalName: 'Beret',
		externalName: 'Beret',
		imageIndex: 19,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_19.png'),
	},
	{
		internalName: 'Wielder Tie',
		externalName: 'Wielder Wrap',
		imageIndex: 21,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_21.png'),
	},
	{
		internalName: 'Rex Head',
		externalName: 'Rex Head',
		imageIndex: 20,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_20.png'),
		showHair: 2,
	},
	{
		internalName: 'Half-Moons',
		externalName: 'Half-Moons',
		imageIndex: 23,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_23.png'),
		showHair: 1,
	},
	{
		internalName: 'Newsie',
		externalName: 'Newsie',
		imageIndex: 22,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_22.png'),
	},
	{
		internalName: 'Pointish Glasses',
		externalName: 'Pointish Glasses',
		imageIndex: 26,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_26.png'),
		showHair: 1,
	},
	{
		internalName: 'Round Glasses',
		externalName: 'Round Glasses',
		imageIndex: 24,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_24.png'),
		showHair: 1,
	},
	{
		internalName: 'Square Glasses',
		externalName: 'Square Glasses',
		imageIndex: 25,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_25.png'),
		showHair: 1,
	},
	{
		internalName: 'Spellcaster',
		externalName: 'Spellcaster',
		imageIndex: 27,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_27.png'),
		showHair: 2,
	},
	{
		internalName: 'Backwards',
		externalName: 'Backwards',
		imageIndex: 28,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_28.png'),
	},
	{
		internalName: 'Feather',
		externalName: 'Feather',
		imageIndex: 29,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_29.png'),
	},
	{
		internalName: 'Ahoy',
		externalName: 'Ahoy',
		imageIndex: 30,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_30.png'),
		showHair: 2,
	},
	{
		internalName: 'Delivery',
		externalName: 'Delivery',
		imageIndex: 31,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_31.png'),
	},
	{
		internalName: 'Earmuffs',
		externalName: 'Earmuffs',
		imageIndex: 32,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_32.png'),
		showHair: 2,
	},
	{
		internalName: 'Clown',
		externalName: 'Clown',
		imageIndex: 33,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_33.png'),
		showHair: 1,
	},
	{
		internalName: 'Wintry',
		externalName: 'Wintry',
		imageIndex: 34,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_34.png'),
	},
	{
		internalName: 'Eyepatch',
		externalName: 'Eyepatch',
		imageIndex: 35,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_35.png'),
		showHair: 1,
	},
	{
		internalName: 'Gnome',
		externalName: 'Gnome',
		imageIndex: 36,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_36.png'),
	},
	{
		internalName: 'Mascot Head',
		externalName: 'Mascot Head',
		imageIndex: 37,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_37.png'),
	},
	{
		internalName: 'Spike Helmet',
		externalName: 'Spike Helmet',
		imageIndex: 38,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_38.png'),
	},
	{
		internalName: 'Big Fungus',
		externalName: 'Big Fungus',
		imageIndex: 39,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_39.png'),
		showHair: 2,
	},
	{
		internalName: 'Nautical',
		externalName: 'Nautical',
		imageIndex: 40,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_40.png'),
	},
	{
		internalName: 'Fungus',
		externalName: 'Fungus',
		imageIndex: 41,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_41.png'),
	},
	{
		internalName: 'Goggles',
		externalName: 'Goggles',
		imageIndex: 42,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_42.png'),
		showHair: 1,
	},
	{
		internalName: 'Headphones',
		externalName: 'Headphones',
		imageIndex: 78,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_78.png'),
		showHair: 2,
	},
	{
		internalName: 'Chef',
		externalName: 'Chef',
		imageIndex: 43,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_43.png'),
	},
	{
		internalName: 'Foxy',
		externalName: 'Foxy',
		imageIndex: 44,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_44.png'),
	},
	{
		internalName: 'Sparkles',
		externalName: 'Sparkles',
		imageIndex: 45,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_45.png'),
		showHair: 1,
	},
	{
		internalName: 'Aviators',
		externalName: 'Aviators',
		imageIndex: 46,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_46.png'),
		showHair: 1,
	},
	{
		internalName: 'Beak',
		externalName: 'Beak',
		imageIndex: 47,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_47.png'),
		showHair: 1,
	},
	{
		internalName: 'Rim Shades',
		externalName: 'Rim Shades',
		imageIndex: 48,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_48.png'),
		showHair: 1,
	},
	{
		internalName: 'Bell',
		externalName: 'Bell',
		imageIndex: 49,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_49.png'),
		showHair: 2,
	},
	{
		internalName: 'Elf',
		externalName: 'Elf',
		imageIndex: 50,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_50.png'),
	},
	{
		internalName: 'Gardener',
		externalName: 'Gardener',
		imageIndex: 51,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_51.png'),
	},
	{
		internalName: 'Stache',
		externalName: 'Stache',
		imageIndex: 52,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_52.png'),
		showHair: 1,
	},
	{
		internalName: 'Monocle',
		externalName: 'Monocle',
		imageIndex: 53,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_53.png'),
		showHair: 1,
	},
	{
		internalName: 'Stormy',
		externalName: 'Stormy',
		imageIndex: 54,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_54.png'),
		showHair: 1,
	},
	{
		internalName: 'Superstar',
		externalName: 'Superstar',
		imageIndex: 55,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_55.png'),
		showHair: 1,
	},
	{
		internalName: 'Shawl',
		externalName: 'Shawl',
		imageIndex: -1,
		layer2ImagePath: require('../images/clothes_padding/sprDog_body2_9.png'),
	},
	{
		internalName: 'Spike',
		externalName: 'Spike',
		imageIndex: -1,
		layer2ImagePath: require('../images/clothes_padding/sprDog_body2_10.png'),
	},
	{
		internalName: 'Studs',
		externalName: 'Studs',
		imageIndex: -1,
		layer2ImagePath: require('../images/clothes_padding/sprDog_body2_11.png'),
	},
	{
		internalName: 'Skate Helmet',
		externalName: 'Skate Helmet',
		imageIndex: 80,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_80.png'),
	},
	{
		internalName: 'Mask',
		externalName: 'Mask',
		imageIndex: 81,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_81.png'),
		showHair: 1,
	},
	{
		internalName: 'Top Hat',
		externalName: 'Top Hat',
		imageIndex: 82,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_82.png'),
		showHair: 2,
	},
	{
		internalName: 'Hajib',
		externalName: 'Headscarf',
		imageIndex: 79,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_79.png'),
	},
	{
		internalName: 'Beard',
		externalName: 'Beard',
		imageIndex: 84,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_84.png'),
		showHair: 1,
	},
	{
		internalName: 'Tiara',
		externalName: 'Tiara',
		imageIndex: 87,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_87.png'),
		showHair: 1,
	},
	{
		internalName: 'Crown',
		externalName: 'Crown',
		imageIndex: 85,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_85.png'),
	},
	{
		internalName: 'Earflap',
		externalName: 'Earflaps',
		imageIndex: 86,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_86.png'),
	},
	{
		internalName: 'PLACEHOLDER_CLOTHES1',
		externalName: 'Helm',
		imageIndex: 83,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_83.png'),
	},
	{
		internalName: 'PLACEHOLDER_CLOTHES2',
		externalName: 'Horns',
		imageIndex: 88,
		imageWithPaddingPath: require('../images/hat_padding/sprDog_hat_88.png'),
		showHair: 89,
		showHairExtraImagePath: require('../images/hat_padding/sprDog_hat_89.png'),
	},
].sort((a, b) => {
	if (a.externalName > b.externalName) {
		return 1;
	}

	if (a.externalName < b.externalName) {
		return -1;
	}

	return 0;
});
